# Generated by Django 5.1 on 2024-08-31 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('website', models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('release_date', models.DateField()),
                ('hardware', models.CharField(choices=[('CPU', 'CPU')], max_length=32)),
                ('classification', models.CharField(choices=[('OPENSOURCE', 'Open Source'), ('FREE', 'Free'), ('PRIVATE', 'Private'), ('COMMERCIAL', 'Commercial')], max_length=32)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openrank.enginefamily')),
            ],
        ),
    ]
