# Generated by Django 5.1 on 2024-08-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0002_engine_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='most_recent',
            field=models.BooleanField(default=False),
        ),
    ]
