# Generated by Django 6.0 on 2026-01-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openrank', '0006_ratinglist_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='tarball_sha',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratinglist',
            name='book_sha',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
