#!/bin/bash

set -e

# Clone the Fastchess repository
echo "Cloning Fastchess repository..."
git clone https://github.com/AndyGrant/Fastchess

# Build Fastchess
echo "Building Fastchess..."
cd Fastchess
make -j build=release

# Move the executable to artifacts directory
echo "Moving fastchess executable to artifacts..."
mv fastchess ../artifacts/

# Get the version and write it to fastchess_ver.py
echo "Capturing fastchess version..."
VERSION=$(../artifacts/fastchess --version | xargs)
cat > ../../openrank/fastchess_ver.py << EOF
# This file is auto-generated by fastchess/prepare_fastchess.sh
FASTCHESS_VERSION = "${VERSION}"
EOF

# Clean up the cloned repository
echo "Cleaning up..."
cd ..
rm -rf Fastchess

echo "Done! fastchess executable is in artifacts/"
echo "Fastchess version: ${VERSION}"
